// @ts-nocheck
import { StyleSheet } from 'react-native';
import { COLORS, FONT, RADIUS, SHADOW, SPACING, TYPE } from '../../utils';

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: SPACING.xl,
    paddingBottom: SPACING.xxl,
  },
  logo: {
    width: 56,
    height: 56,
    borderRadius: 14,
    alignSelf: 'center',
    marginBottom: SPACING.lg,
  },
  headline: {
    ...TYPE.sectionTitle,
    fontSize: 26,
    textAlign: 'center',
    marginBottom: SPACING.xs,
  },
  headlineAccent: { color: COLORS.navy2 },
  subheadline: {
    ...TYPE.body,
    color: COLORS.textMuted,
    textAlign: 'center',
    marginBottom: SPACING.xl,
  },
  formCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SHADOW.card,
  },
  primaryBtn: {
    backgroundColor: COLORS.navy2,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md + 4,
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  primaryBtnText: {
    fontFamily: FONT,
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryBtn: {
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md + 4,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.navy2,
    marginBottom: SPACING.lg,
    backgroundColor: COLORS.white,
  },
  secondaryBtnText: {
    fontFamily: FONT,
    color: COLORS.navy2,
    fontSize: 16,
    fontWeight: '700',
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  footerMuted: { fontSize: 14, color: COLORS.textMuted, fontFamily: FONT },
  footerLink: { fontSize: 14, fontWeight: '700', color: COLORS.navy2, fontFamily: FONT },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.xl,
    width: '100%',
    marginBottom: SPACING.lg,
    ...SHADOW.card,
  },
  cardLabel: {
    fontSize: 11,
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: SPACING.xs,
    fontFamily: FONT,
  },
  cardName: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: SPACING.xs,
    fontFamily: FONT,
  },
  cardMuted: {
    fontSize: 14,
    color: COLORS.textMuted,
    marginTop: 2,
    fontFamily: FONT,
  },
  cardWarn: { fontSize: 13, color: COLORS.gold, marginTop: SPACING.md, textAlign: 'center', fontFamily: FONT },
  cardError: { fontSize: 13, color: COLORS.red, marginTop: SPACING.sm, textAlign: 'center', fontFamily: FONT },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SHADOW.soft,
  },
  menuRowText: { flex: 1, ...TYPE.label, fontSize: 15, color: COLORS.text },
  menuChevron: { fontSize: 18, color: COLORS.textMuted },
});
